version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: prisma_user
      POSTGRES_PASSWORD: prisma_password
      POSTGRES_DB: prisma_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
